# -*- coding: utf-8 -*-
"""Untitled36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gw-UsOgz1DXvt25kAsdgf_Qrn4zCQVKR
"""

!pip install streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# 
# st.title("Mi Primera App")
# st.write("Hola desde Streamlit")
#