-*- coding: utf-8 -*-
"""Untitled28.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TgKik8x3FnVLGL4gC8B1Ouy9DqoZKvH6
"""

 Commented out IPython magic to ensure Python compatibility.
 %%writefile app.py
 import math
 import matplotlib.pyplot as plt
 import numpy as np
 import pandas as pd
 import streamlit as st
 
  --- CONFIGURACIÓN INICIAL DE LA PÁGINA ---
 st.set_page_config(
     page_title="Simulador de Alineación y Colimación Óptica", layout="wide"
 )
 
  #--- DICCIONARIOS DE TRADUCCIÓN E IDIOMA ---
 TEXTS = {
     "ES": {
         "title": "Simulador de Alineación y Colimación Óptica",
         "lang_select": "Idioma / Language",
         "unit_select": "Sistema de Unidades / Unit System",
         "metric": "Métrico (cm, metros)",
         "imperial": "Imperial (pulgadas, yardas)",
         "profile_select": "Perfil de Aplicación / Profesión",
         "profile_placeholder": "-- Seleccione una Profesión / Carrera --",
         "p1": "Calibración de brazos robóticos",
         "p2": "Alineación de maquinaria industrial",
         "p3": "Topografía y construcción civil",
         "p4": "Alineación de colectores solares / Helióstatos",
         "p5": "Guiado láser de robótica móvil",
         "p6": "Guiado de maquinaria de tunelación",
         "p7": "Alineación de Puentes Colgantes",
         "p8": "Nivelación de Vías de Tren de Alta Velocidad",
         "p9": "Montacargas Autónomos en Almacenes 3D",
         "p10": "Clasificación de Paquetes por Bandas",
         "p11": "Alineación de Antenas Satelitales",
         "p12": "Calibración de Sensores de Aterrizaje",
         "p13": "Alineación de Hélices en Torres Eólicas",
         "p14": "Inspección Óptica de Cascos de Barcos",
         "p15": "Guiado de Perforadoras en Minería",
         "p16": "Colimación de Telescopios Astronómicos",
         "p17": "Alineación de Espejos Láser Quirúrgicos",
         "p18": "Guiado Optoelectrónico de Misiles Defensivos",
         "p19": "Calibración de Sensores LiDAR Automotrices",
         "p20": "Centrado de Turbinas Hidroeléctricas",
         "p21": "Inspección de Deformación en Turbinas de Gas",
         "p22": "Nivelación de Plataformas Petroleras Offshore",
         "p23": "Alineación de Escáneres LiDAR en Drones",
         "p24": "Colimación de Sistemas Ópticos Micro litográficos",
         "p25": "Control de Flexión en Estructuras de Estadios",
         "mode_label": "Modo de Interfaz",
         "mode_simple": "Modo Simple (Principiante)",
         "mode_advanced": "Modo Avanzado (Pro)",
         "help_title": "¿Cómo funciona esta herramienta? (Guía Rápida)",
         "help_body": """
  #Guía de Uso Paso a Paso:
 1. **Selecciona tu Perfil:** En el panel izquierdo, elige la carrera o profesión aplicable.
 2. **Modo Simple vs. Avanzado:**
    - **Modo Simple:** Configura solo la distancia y elevación esencial.
    - **Modo Avanzado:** Permite ajustar tolerancias de precisión (*Pasa/No Pasa*) y desviación horizontal por viento (*Azimut*).
 3. **Línea de Colimación ($H_{mira}$):** Altura desde la base hasta el centro del sensor/visor.
 4. **Desviación ($H_{extra}$):** Desplazamiento respecto al centro deseado.
 5. **Distancia ($D$):** Trayectoria horizontal hacia el objetivo.
 """,
         "params": "Parámetros de Entrada",
         "reset_btn": "Reiniciar Valores a 0",
         "save_btn": "Registrar Medición",
         "h_mira": "Línea de colimación",
         "h_extra": "Desviación del punto de impacto / Objetivo",
         "dist_input": "Distancia al receptor / Destino",
         "ref_angle_input": "Inclinación del eje óptico de referencia (°)",
         "cm": "cm",
         "m": "m",
         "in": "pulgadas",
         "yd": "yardas",
         "laser_label": "Eje óptico de referencia",
         "sight_label": "Eje del sensor ajustable",
         "target_center": "Centro del Objetivo",
         "target_point": "Punto Requerido",
         "title_graph": "Distancia",
         "diff_height": "Diferencia Altura",
         "sight_angle": "Ángulo de Inclinación (α)",
         "direction_up": "Arriba",
         "direction_down": "Abajo",
         "history_title": "Historial de Registros Guardados",
         "clear_history": "Borrar Historial",
         "confirm_clear": "¿Está seguro de que desea borrar el historial?",
         "btn_confirm_yes": "Sí, borrar",
         "btn_cancel": "Cancelar",
         "empty_history": "No hay registros guardados en el historial.",
         "select_prompt": "Por favor, seleccione un Perfil de Aplicación / Profesión en la barra lateral para iniciar la simulación.",
         "record_saved": "Medición registrada en el historial.",
         "tol_header": "Control de Tolerancia (Pasa/No Pasa)",
         "tol_label": "Tolerancia Máxima Permitida",
         "status_pass": "DENTRO DE TOLERANCIA",
         "status_fail": "FUERA DE TOLERANCIA",
         "lat_header": "Desviación Lateral / Viento (Eje X)",
         "lat_dev": "Desviación Horizontal (Eje X)",
         "left": "Izquierda",
         "right": "Derecha",
         "centered": "Centrado",
         "lat_adj": "Ajuste Azimutal (X)",
         "view_side": "Corte Vertical (Elevación Y-Z)",
         "view_top": "Vista Superior (Azimut X-Z)",
         "tol_band": "Zona de Tolerancia",
     },
     "EN": {
         "title": "Optical Alignment & Collimation Simulator",
         "lang_select": "Language / Idioma",
         "unit_select": "Unit System / Sistema de Unidades",
         "metric": "Metric (cm, meters)",
         "imperial": "Imperial (inches, yards)",
         "profile_select": "Application Profile / Profession",
         "profile_placeholder": "-- Select a Profession / Career --",
         "p1": "Robotic Arm Calibration",
         "p2": "Industrial Machinery Alignment",
         "p3": "Surveying & Civil Construction",
         "p4": "Solar Collector / Heliostat Alignment",
         "p5": "Mobile Robotics Laser Guidance",
         "p6": "Tunneling Machinery Guidance",
         "p7": "Suspension Bridge Alignment",
         "p8": "High-Speed Train Track Leveling",
         "p9": "Autonomous Forklifts in 3D Warehouses",
         "p10": "Belt Package Sorting Systems",
         "p11": "Satellite Dish Alignment",
         "p12": "Aircraft Landing Sensor Calibration",
         "p13": "Wind Turbine Blade Alignment",
         "p14": "Ship Hull Optical Inspection",
         "p15": "Open-Pit Mining Drill Guidance",
         "p16": "Astronomical Telescope Collimation",
         "p17": "Surgical Laser Mirror Alignment",
         "p18": "Defensive Missile Optoelectronic Guidance",
         "p19": "Automotive LiDAR Sensor Calibration",
         "p20": "Hydroelectric Turbine Centering",
         "p21": "Gas Turbine Strain Inspection",
         "p22": "Offshore Oil Rig Platform Leveling",
         "p23": "Drone LiDAR Scanner Alignment",
         "p24": "Microlithographic Optical System Collimation",
         "p25": "Stadium Roof Deflection Monitoring",
         "mode_label": "Interface Mode",
         "mode_simple": "Simple Mode (Beginner)",
         "mode_advanced": "Advanced Mode (Pro)",
         "help_title": "How to use this tool? (Quick Guide)",
         "help_body": """
  Step-by-Step Guide:
 1. **Select your Profile:** Choose your applicable career or profession in the left sidebar.
 2. **Simple vs. Advanced Mode:**
    - **Simple Mode:** Adjust basic distance and height variables.
    - **Advanced Mode:** Enables precision tolerances (*Pass/Fail*) and horizontal drift adjustments (*Azimuth*).
 3. **Collimation Line ($H_{mira}$):** Height from base to target/sight center.
 4. **Target Offset ($H_{extra}$):** Offset from desired center.
 5. **Distance ($D$):** Horizontal trajectory distance.
 """,
         "params": "Input Parameters",
         "reset_btn": "Reset Values to 0",
         "save_btn": "Save Measurement",
         "h_mira": "Collimation Line",
         "h_extra": "Impact Point Deviation / Target Offset",
         "dist_input": "Distance to Receiver / Destination",
         "ref_angle_input": "Reference Optical Axis Inclination (°)",
         "cm": "cm",
         "m": "m",
         "in": "inches",
         "yd": "yards",
         "laser_label": "Reference Optical Axis",
         "sight_label": "Adjustable Sensor Axis",
         "target_center": "Target Center",
         "target_point": "Required Point",
         "title_graph": "Distance",
         "diff_height": "Height Difference",
         "sight_angle": "Inclination Angle (α)",
         "direction_up": "Up",
         "direction_down": "Down",
         "history_title": "Saved Records History",
         "clear_history": "Clear History",
         "confirm_clear": "Are you sure you want to clear the history?",
         "btn_confirm_yes": "Yes, clear",
         "btn_cancel": "Cancel",
         "empty_history": "No records saved in history yet.",
         "select_prompt": "Please select an Application Profile / Profession in the sidebar to start the simulation.",
         "record_saved": "Measurement saved into history.",
         "tol_header": "Tolerance Control (Pass/Fail)",
         "tol_label": "Max Allowed Tolerance",
         "status_pass": "WITHIN TOLERANCE",
         "status_fail": "OUT OF TOLERANCE",
         "lat_header": "Lateral Drift / Wind (X-Axis)",
         "lat_dev": "Horizontal Deviation (X-Axis)",
         "left": "Left",
         "right": "Right",
         "centered": "Centered",
         "lat_adj": "Azimuth Adjustment (X)",
         "view_side": "Vertical Cut (Elevation Y-Z)",
         "view_top": "Vista Superior (Azimut X-Z)",
         "tol_band": "Tolerance Zone",
     },
 }
 
 # --- SELECCIÓN DE IDIOMA ---
 st.sidebar.header("Configuración / Settings")
 lang = st.sidebar.selectbox("Idioma / Language", ["Español", "English"])
 lang_code = "ES" if lang == "Español" else "EN"
 txt = TEXTS[lang_code]
 
 # --- MODO SIMPLE VS. AVANZADO ---
 is_advanced_mode = st.sidebar.toggle(txt["mode_label"], value=False)
 st.sidebar.caption(
     txt["mode_advanced"] if is_advanced_mode else txt["mode_simple"]
 )
 
 st.sidebar.divider()
 
 # --- MENÚ DESPLEGABLE DE PROFESIONES ---
 st.sidebar.header(txt["profile_select"])
 profiles_options = [txt["profile_placeholder"]] + [
     txt["p1"],
     txt["p2"],
     txt["p3"],
     txt["p4"],
     txt["p5"],
     txt["p6"],
     txt["p7"],
     txt["p8"],
     txt["p9"],
     txt["p10"],
     txt["p11"],
     txt["p12"],
     txt["p13"],
     txt["p14"],
     txt["p15"],
     txt["p16"],
     txt["p17"],
     txt["p18"],
     txt["p19"],
     txt["p20"],
     txt["p21"],
     txt["p22"],
     txt["p23"],
     txt["p24"],
     txt["p25"],
 ]
 
 profile = st.sidebar.selectbox(
     txt["profile_select"], profiles_options, index=0
 )
 
 PROFILE_PRESETS = {
     txt["p1"]: (True, 1.2, 0.15, 1.5, 0.05, 0.05),
     txt["p2"]: (True, 2.5, 0.50, 6.0, 0.20, 0.10),
     txt["p3"]: (False, 4.0, 1.50, 120.0, 1.20, 0.50),
     txt["p4"]: (True, 12.0, 4.50, 350.0, 2.80, 1.00),
     txt["p5"]: (True, 8.0, -2.10, 650.0, -1.50, 0.80),
     txt["p6"]: (True, 25.0, -8.00, 1200.0, 3.50, 2.00),
     txt["p7"]: (False, 10.0, 3.20, 850.0, 2.10, 1.20),
     txt["p8"]: (True, 4.5, 0.80, 180.0, 0.45, 0.20),
     txt["p9"]: (True, 3.0, 1.20, 18.0, 2.50, 0.30),
     txt["p10"]: (True, 0.5, 0.05, 2.5, 0.10, 0.02),
     txt["p11"]: (True, 35.0, 12.00, 1500.0, 8.50, 3.00),
     txt["p12"]: (False, 5.0, -1.80, 320.0, -2.10, 0.50),
     txt["p13"]: (True, 5.0, -1.20, 12.0, -0.80, 0.40),
     txt["p14"]: (True, 15.0, 2.80, 75.0, 0.90, 0.80),
     txt["p15"]: (False, 6.0, -2.50, 1100.0, -4.20, 1.50),
     txt["p16"]: (True, 45.0, 15.00, 2000.0, 12.00, 0.01),
     txt["p17"]: (True, 0.2, 0.04, 0.8, 0.05, 0.005),
     txt["p18"]: (True, 50.0, -10.00, 1800.0, -14.00, 2.50),
     txt["p19"]: (True, 6.5, 1.10, 80.0, 1.50, 0.15),
     txt["p20"]: (True, 1.8, -0.30, 12.0, -0.40, 0.05),
     txt["p21"]: (True, 0.9, 0.12, 4.5, 0.25, 0.02),
     txt["p22"]: (False, 14.0, 4.50, 650.0, 3.80, 1.00),
     txt["p23"]: (True, 2.8, -0.50, 45.0, -1.20, 0.25),
     txt["p24"]: (True, 0.1, 0.01, 0.3, 0.02, 0.001),
     txt["p25"]: (True, 20.0, 4.20, 220.0, 2.90, 0.90),
 }
 
 if "current_profile" not in st.session_state:
     st.session_state["current_profile"] = profile
 
 if profile != st.session_state["current_profile"]:
     st.session_state["current_profile"] = profile
     if profile in PROFILE_PRESETS:
         pref_metric, h_m, h_e, dist, angle, tol = PROFILE_PRESETS[profile]
         st.session_state["unit_choice"] = (
             txt["metric"] if pref_metric else txt["imperial"]
         )
         st.session_state["h_mira_val"] = h_m
         st.session_state["h_extra_val"] = h_e
         st.session_state["dist_val"] = dist
         st.session_state["ref_angle_val"] = angle
         st.session_state["tol_val"] = tol
         st.session_state["lat_dev_val"] = 0.0
     else:
         st.session_state["h_mira_val"] = 0.0
         st.session_state["h_extra_val"] = 0.0
         st.session_state["dist_val"] = 0.0
         st.session_state["ref_angle_val"] = 0.0
         st.session_state["tol_val"] = 0.5
         st.session_state["lat_dev_val"] = 0.0
 
 if "unit_choice" not in st.session_state:
     st.session_state["unit_choice"] = txt["metric"]
 
 unit_sys = st.sidebar.radio(
     txt["unit_select"], [txt["metric"], txt["imperial"]], key="unit_choice"
 )
 is_metric = unit_sys == txt["metric"]
 
 if "h_mira_val" not in st.session_state:
     st.session_state["h_mira_val"] = 0.0
 if "h_extra_val" not in st.session_state:
     st.session_state["h_extra_val"] = 0.0
 if "dist_val" not in st.session_state:
     st.session_state["dist_val"] = 0.0
 if "ref_angle_val" not in st.session_state:
     st.session_state["ref_angle_val"] = 0.0
 if "tol_val" not in st.session_state:
     st.session_state["tol_val"] = 0.5
 if "lat_dev_val" not in st.session_state:
     st.session_state["lat_dev_val"] = 0.0
 if "history" not in st.session_state:
     st.session_state["history"] = []
 if "confirm_delete" not in st.session_state:
     st.session_state["confirm_delete"] = False
 
 
 def reset_inputs_to_zero():
     st.session_state["h_mira_val"] = 0.0
     st.session_state["h_extra_val"] = 0.0
     st.session_state["dist_val"] = 0.0
     st.session_state["ref_angle_val"] = 0.0
     st.session_state["tol_val"] = 0.5
     st.session_state["lat_dev_val"] = 0.0
 
 
 st.sidebar.header(txt["params"])
 
 if is_metric:
     h_unit, d_unit = txt["cm"], txt["m"]
 else:
     h_unit, d_unit = txt["in"], txt["yd"]
 
 H_mira = st.sidebar.number_input(
     f"{txt['h_mira']} ({h_unit})",
     min_value=-500.0,
     max_value=500.0,
     value=st.session_state["h_mira_val"],
     step=0.1,
     key="h_mira_val",
 )
 H_extra = st.sidebar.number_input(
     f"{txt['h_extra']} ({h_unit})",
     min_value=-500.0,
     max_value=500.0,
     value=st.session_state["h_extra_val"],
     step=0.1,
     key="h_extra_val",
 )
 D_val = st.sidebar.number_input(
     f"{txt['dist_input']} ({d_unit})",
     min_value=0.0,
     max_value=2000.0,
     value=st.session_state["dist_val"],
     step=1.0,
     key="dist_val",
 )
 ref_angle_deg = st.sidebar.number_input(
     txt["ref_angle_input"],
     min_value=-30.00,
     max_value=30.00,
     value=st.session_state["ref_angle_val"],
     step=0.10,
     format="%.2f",
     key="ref_angle_val",
 )
 
 if is_advanced_mode:
     with st.sidebar.expander(f"1. {txt['tol_header']}", expanded=True):
         tolerance_val = st.number_input(
             f"{txt['tol_label']} ({h_unit})",
             min_value=0.0,
             max_value=50.0,
             value=st.session_state["tol_val"],
             step=0.05,
             format="%.3f",
             key="tol_val",
         )
 
     with st.sidebar.expander(f"3. {txt['lat_header']}", expanded=True):
         lat_dev_val = st.number_input(
             f"{txt['lat_dev']} ({h_unit})",
             min_value=-200.0,
             max_value=200.0,
             value=st.session_state["lat_dev_val"],
             step=0.1,
             key="lat_dev_val",
         )
 else:
     tolerance_val = st.session_state["tol_val"]
     lat_dev_val = 0.0
 
 save_clicked = st.sidebar.button(txt["save_btn"], use_container_width=True)
 st.sidebar.button(
     txt["reset_btn"], on_click=reset_inputs_to_zero, use_container_width=True
 )
 
 if is_metric:
     D_cm, H_mira_cm, H_extra_cm = D_val * 100, H_mira, H_extra
     lat_dev_cm, tol_cm = lat_dev_val, tolerance_val
 else:
     D_cm, H_mira_cm, H_extra_cm = D_val * 91.44, H_mira * 2.54, H_extra * 2.54
     lat_dev_cm, tol_cm = lat_dev_val * 2.54, tolerance_val * 2.54
 
 with st.expander(txt["help_title"], expanded=False):
     st.markdown(txt["help_body"])
 
 header_html = f"""<div style="background: linear-gradient(180deg, 18181B 0%, 121214 100%); padding: 16px 25px; border-radius: 8px; border: 1px solid 27272A; border-left: 4px solid FFFFFF; margin-bottom: 20px;"><h2 style="color: FFFFFF; margin: 0; font-size: 20px; font-family: 'Segoe UI', sans-serif; font-weight: 600;">{txt['title']}</h2><p style="color: A1A1AA; margin: 4px 0 0 0; font-size: 13px;">Alineación de precisión óptica &nbsp;|&nbsp; Perfil Activo: <span style="color: FFFFFF; font-weight: 600;">{profile if profile != txt['profile_placeholder'] else 'Ninguno'}</span></p></div>"""
 st.markdown(header_html, unsafe_allow_html=True)
 
 if profile == txt["profile_placeholder"]:
     st.warning(txt["select_prompt"])
     st.stop()
 
 ref_angle_rad = math.radians(ref_angle_deg)
 y_ref_end = D_cm * math.tan(ref_angle_rad)
 y_target_point = y_ref_end + H_extra_cm
 diferencia_altura_cm = y_target_point - H_mira_cm
 
 if D_cm > 0:
     angulo_rad = math.atan(diferencia_altura_cm / D_cm)
     lat_angle_rad = math.atan(lat_dev_cm / D_cm)
 else:
     angulo_rad, lat_angle_rad = 0.0, 0.0
 
 angulo_deg = math.degrees(angulo_rad)
 moa, mrad = angulo_deg * 60, angulo_rad * 1000
 diff_height_display = (
     diferencia_altura_cm if is_metric else diferencia_altura_cm / 2.54
 )
 
 lat_angle_deg = math.degrees(lat_angle_rad)
 lat_moa = lat_angle_deg * 60
 lat_dir = (
     txt["right"]
     if lat_dev_val > 0
     else (txt["left"] if lat_dev_val < 0 else txt["centered"])
 )
 
 err_total_cm = math.sqrt(diferencia_altura_cm**2 + lat_dev_cm**2)
 err_total_disp = err_total_cm if is_metric else err_total_cm / 2.54
 
 is_within_tolerance = err_total_disp <= tolerance_val
 status_text = txt["status_pass"] if is_within_tolerance else txt["status_fail"]
 status_color = "10B981" if is_within_tolerance else "EF4444"
 
 is_up = angulo_deg >= 0
 
 if save_clicked:
     current_record = {
         "Perfil / Carrera": profile,
         "Distancia": f"{D_val:.1f} {d_unit}",
         "Línea Colimación": f"{H_mira:.2f} {h_unit}",
         "Desviación Vert.": f"{diff_height_display:.2f} {h_unit}",
         "Ángulo Elev. (α)": f"{angulo_deg:.4f}°",
         "Ajuste Elev.": f"{moa:.2f} MOA",
     }
     if is_advanced_mode:
         current_record.update(
             {
                 "Desviación Horiz.": f"{lat_dev_val:.2f} {h_unit}",
                 "Ajuste Azimut": f"{lat_moa:.2f} MOA ({lat_dir})",
                 "Tolerancia": f"±{tolerance_val:.2f} {h_unit}",
                 "Estado": status_text,
             }
         )
     st.session_state["history"].append(current_record)
     st.sidebar.success(txt["record_saved"])
 
 if is_advanced_mode:
     tab_side, tab_top = st.tabs([txt["view_side"], txt["view_top"]])
 else:
     tab_side = st.container()
 
 with tab_side:
     fig_side, ax_side = plt.subplots(figsize=(10, 4.2))
     pos_laser, pos_mira = (0, 0), (0, H_mira_cm)
     pos_diana_centro, pos_impacto_mira = (D_cm, y_ref_end), (
         D_cm,
         y_target_point,
     )
 
     x_min, x_max = -max(D_cm, 10) * 0.1, max(D_cm, 10) * 1.15
     y_raw_min = (
         min(0, pos_mira[1], pos_diana_centro[1], pos_impacto_mira[1])
         - tol_cm
     )
     y_raw_max = (
         max(0, pos_mira[1], pos_diana_centro[1], pos_impacto_mira[1])
         + tol_cm
     )
     y_range = max(abs(y_raw_max - y_raw_min), 10.0)
     y_bottom, y_top = y_raw_min - (y_range * 0.05), y_raw_max + (y_range * 0.05)
 
     ax_side.set_facecolor("0A0A0B")
     fig_side.patch.set_facecolor("0A0A0B")
 
     if is_advanced_mode:
         ax_side.fill_between(
             [D_cm * 0.85, D_cm * 1.15],
             y_target_point - tol_cm,
             y_target_point + tol_cm,
             color="10B981",
             alpha=0.15,
             label=txt["tol_band"],
         )
 
     ax_side.plot(
         [0, D_cm],
         [0, y_ref_end],
         color="71717A",
         linestyle="--",
         linewidth=1.5,
         label=f"{txt['laser_label']} ({ref_angle_deg:.2f}°)",
     )
     ax_side.plot(
         [0, D_cm],
         [pos_mira[1], pos_impacto_mira[1]],
         color="FFFFFF",
         linestyle="-",
         linewidth=2.0,
         label=f'{txt["sight_label"]} (α = {angulo_deg:.2f}°)',
     )
 
     SIZE_SMALL, SIZE_LARGE = 140, 160
     ax_side.scatter(*pos_laser, color="A1A1AA", s=SIZE_SMALL, marker="s", zorder=6)
     ax_side.scatter(*pos_mira, color="E4E4E7", s=SIZE_SMALL, marker="^", zorder=6)
     ax_side.scatter(
         *pos_diana_centro,
         color="71717A",
         s=SIZE_LARGE,
         marker="o",
         edgecolors="FFFFFF",
         linewidth=1.5,
         zorder=6,
         label=txt["target_center"],
     )
     ax_side.scatter(
         *pos_impacto_mira,
         color="FFFFFF" if is_within_tolerance else "EF4444",
         s=SIZE_LARGE,
         marker="D",
         edgecolors="0A0A0B",
         linewidth=1.5,
         zorder=6,
         label=txt["target_point"],
     )
 
     ax_side.set_title(
         f"{txt['title_graph']}: {D_val:.1f} {d_unit} | Elevación: {angulo_deg:.4f}° ({moa:.1f} MOA)",
         color="E4E4E7",
         fontsize=10,
         fontweight="bold",
         pad=12,
     )
     ax_side.set_xlim(x_min, x_max)
     ax_side.set_ylim(y_bottom, y_top)
     ax_side.grid(True, linestyle=":", alpha=0.15, color="FFFFFF")
     ax_side.tick_params(colors="A1A1AA", labelsize=8)
 
     for spine in ax_side.spines.values():
         spine.set_color("27272A")
 
     ax_side.legend(
         loc="upper center",
         bbox_to_anchor=(0.5, -0.15),
         ncol=4,
         facecolor="121214",
         edgecolor="27272A",
         labelcolor="E4E4E7",
         framealpha=1.0,
         fontsize=8,
     )
 
     st.pyplot(fig_side)
 
 if is_advanced_mode:
     with tab_top:
         fig_top, ax_top = plt.subplots(figsize=(10, 4.2))
         ax_top.set_facecolor("0A0A0B")
         fig_top.patch.set_facecolor("0A0A0B")
 
         ax_top.fill_between(
             [D_cm * 0.85, D_cm * 1.15],
             -tol_cm,
             tol_cm,
             color="10B981",
             alpha=0.15,
             label=txt["tol_band"],
         )
         ax_top.plot(
             [0, D_cm],
             [0, 0],
             color="71717A",
             linestyle="--",
             linewidth=1.5,
             label="Eje Central Azimut",
         )
         ax_top.plot(
             [0, D_cm],
             [0, lat_dev_cm],
             color="38BDF8",
             linestyle="-",
             linewidth=2.0,
             label=f"Desviación Azimutal ({lat_moa:.2f} MOA)",
         )
 
         ax_top.scatter(
             0, 0, color="A1A1AA", s=SIZE_SMALL, marker="s", zorder=6
         )
         ax_top.scatter(
             D_cm,
             0,
             color="71717A",
             s=SIZE_LARGE,
             marker="o",
             edgecolors="FFFFFF",
             linewidth=1.5,
             zorder=6,
             label=txt["target_center"],
         )
         ax_top.scatter(
             D_cm,
             lat_dev_cm,
             color="38BDF8" if abs(lat_dev_val) <= tolerance_val else "EF4444",
             s=SIZE_LARGE,
             marker="D",
             edgecolors="0A0A0B",
             linewidth=1.5,
             zorder=6,
         )
 
         ax_top.set_xlim(x_min, x_max)
         max_lat_bound = max(abs(lat_dev_cm), tol_cm, 5.0) * 1.5
         ax_top.set_ylim(-max_lat_bound, max_lat_bound)
         ax_top.set_title(
             f"Vista Superior / Azimut (X-Z) | Desviación Lateral: {lat_dev_val:.2f} {h_unit}",
             color="E4E4E7",
             fontsize=10,
             fontweight="bold",
             pad=12,
         )
         ax_top.grid(True, linestyle=":", alpha=0.15, color="FFFFFF")
         ax_top.tick_params(colors="A1A1AA", labelsize=8)
 
         for spine in ax_top.spines.values():
             spine.set_color("27272A")
 
         ax_top.legend(
             loc="upper center",
             bbox_to_anchor=(0.5, -0.15),
             ncol=3,
             facecolor="121214",
             edgecolor="27272A",
             labelcolor="E4E4E7",
             framealpha=1.0,
             fontsize=8,
         )
 
         st.pyplot(fig_top)
 
 # --- TARJETAS DE MÉTRICAS INDIVIDUALES ---
 st.markdown("<br>", unsafe_allow_html=True)
 
 if is_advanced_mode:
     cols = st.columns(5)
     with cols[0]:
         st.metric(
             label=txt["diff_height"], value=f"{diff_height_display:.2f} {h_unit}"
         )
     with cols[1]:
         st.metric(label=txt["sight_angle"], value=f"{angulo_deg:.4f}°")
     with cols[2]:
         st.metric(label="Ajuste Elevación", value=f"{moa:.2f} MOA")
     with cols[3]:
         st.metric(label=txt["lat_adj"], value=f"{lat_moa:.2f} MOA")
     with cols[4]:
         st.metric(label="Estado", value=status_text)
 else:
     cols = st.columns(3)
     with cols[0]:
         st.metric(
             label=txt["diff_height"], value=f"{diff_height_display:.2f} {h_unit}"
         )
     with cols[1]:
         st.metric(label=txt["sight_angle"], value=f"{angulo_deg:.4f}°")
     with cols[2]:
         st.metric(label="Ajuste Elevación", value=f"{moa:.2f} MOA")
 
 # --- HISTORIAL Y BORRADO ---
 st.markdown(
     "<hr style='border-color: 27272A; margin: 30px 0;'>", unsafe_allow_html=True
 )
 col_hist_head, col_hist_btn = st.columns([3, 1])
 
 with col_hist_head:
     st.subheader(txt["history_title"])
 
 with col_hist_btn:
     if not st.session_state["confirm_delete"]:
         if st.button(txt["clear_history"], use_container_width=True):
             st.session_state["confirm_delete"] = True
             st.rerun()
 
 if st.session_state["confirm_delete"]:
     st.warning(txt["confirm_clear"])
     col_yes, col_no = st.columns(2)
     with col_yes:
         if st.button(txt["btn_confirm_yes"], use_container_width=True):
             st.session_state["history"] = []
             st.session_state["confirm_delete"] = False
             st.rerun()
     with col_no:
         if st.button(txt["btn_cancel"], use_container_width=True):
             st.session_state["confirm_delete"] = False
             st.rerun()
 
 if st.session_state["history"]:
     df_history = pd.DataFrame(st.session_state["history"])
     st.dataframe(df_history, use_container_width=True, hide_index=True)
 else:
     st.info(txt["empty_history"])
